main/blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path("", HomeViews.as_view(), name="home"),
    path("category/<int:category_id>/", PostByCategory.as_view(), name="category"),
    path("post/<int:pk>/", ViewPost.as_view(), name="views_post"),
    path("post/add-post/", CreatePost.as_view(), name="add_post"),
    path("post/update/<int:pk>/", UpdatePost.as_view(), name="update_post"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('user-posts/', UserPostListView.as_view(), name='user_posts'),
    path('delete_comment/<int:comment_id>/', ViewPost.delete_comment, name='delete_comment'),
    path('signup/', signup, name='signup'),
    path('help/', help, name='help'),
    path('confidence/', confidence, name='confidence'),
    path('doc/', doc, name='doc'),
    path('rules/', rules, name='rules'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
]

main/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Админка '
admin.site.site_title = 'Админка сайта'

main/blog/models.py
from email.mime import image
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import RegexValidator


class Post(models.Model):
    title = models.CharField(max_length=150, verbose_name="Заголовок")
    content = models.TextField(blank=True, verbose_name="Текст объявления")
    author = models.ForeignKey(User, related_name='author', on_delete=models.CASCADE)
    created_ad = models.DateTimeField(auto_now_add="True", verbose_name="Дата создания")
    updated_ad = models.DateTimeField(auto_now="True", verbose_name="Дата обновления")
    photo = models.ImageField(blank=True, null=True, verbose_name="Фото",default='default.jpg')
    price = models.PositiveIntegerField(verbose_name="Цена", default=0)
    is_published = models.BooleanField(default=True, verbose_name="Активное?")
    category = models.ForeignKey(
        "Category",
        on_delete=models.PROTECT,
        verbose_name="Категории",
        default=1
    )

    def get_absolute_url(self):
        return reverse("views_post", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Объявления"
        verbose_name_plural = "Объявление"
        ordering = ["-updated_ad"]

class PostImage(models.Model):
    post = models.ForeignKey(Post, related_name='images', on_delete=models.CASCADE)
    images = models.ImageField(upload_to="photos", verbose_name='Фото', blank=True)

    # def __str__(self):
    #     return self.post.title
    class Meta:
        verbose_name = "Фото"

class Category(models.Model):
    icon = models.ImageField(upload_to="icons/",blank=True, null=True, verbose_name="Иконка")
    title = models.CharField(
        max_length=150, db_index=True, verbose_name="Название категории")
    parent_category = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def get_absolute_url(self):
        return reverse("category", kwargs={"category_id": self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"
        ordering = ["id"]


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete = models.CASCADE)
    name = models.CharField('Ваше имя', max_length=80)
    parent = models.ForeignKey('self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True)
    body = models.TextField('Комментарий')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"
        ordering = ('-created',)

    def __str__(self):
        return 'Комментарий {} от {}'.format(self.name, self.post)


class Help(models.Model):
    name = models.CharField('Ваше имя', max_length=80)
    body = models.TextField('Текст обращения')
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Телефон должнен быть похож на: '+999999999'. ")
    phone = models.CharField(validators=[phone_regex], max_length=17, blank=True, verbose_name="Телефон") 
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Обращение в техподдежку"
        verbose_name_plural = "Техподдержка"
        ordering = ('-created',)

    def __str__(self):
        return '{} Обращение от {}: {}'.format(self.created, self.name, self.body)

main/templates/inc/_nav.html
{% load blog_tags %}
<!-- Navbar -->
<nav class="fixed-top navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Eleventh navbar example">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">1Й МОРСКОЙ</a>
    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse" id="navbarsExample09" >
      <div class="col-lg-5 offset-lg-1">
        <form action="{% url 'search_results' %}" method="get" class="input-group">
          <input name="q" type="text" placeholder="Поиск по объявлениям" class="form-control" aria-describedby="button-addon2">
          <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Поиск</title><circle cx="10.5" cy="10.5" r="7.5"></circle><path d="M21 21l-5.2-5.2"></path></svg>
          </button>
        </form>
      </div>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'add_post' %}">Добавить объявление</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown09" data-bs-toggle="dropdown" aria-expanded="false">{{ user.get_username }}</a>
          
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown09">
            <li><a href="{% url 'users-profile' %}" class="dropdown-item">Профиль</a></li>
              <li><a href="{% url 'add_post' %}" class="dropdown-item">Добавить объявление</a></li>
              <li><a href="{% url 'user_posts' %}" class="dropdown-item">Мои объявления</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a href="{% url 'home' %}" class="dropdown-item">Помощь</a></li>
              <li><a href="{% url 'logout' %}" class="dropdown-item">Выйти</a></li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users-register' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>


<nav class="fixed-top scrolling-navbar bg-white">
  <div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-between py-3 border-bottom">
      <a class="navbar-brand waves-effect d-none d-lg-block" href="{% url 'home' %}">
        <strong class="blue-text">1й МОРСКОЙ</strong>
      </a>
    
        <form action="{% url 'search_results' %}" method="get" class="input-group search-form" >
          <input name="q" type="text" placeholder="Поиск по объявлениям" class="form-control" aria-describedby="button-addon2">
          <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Поиск</title><circle cx="10.5" cy="10.5" r="7.5"></circle><path d="M21 21l-5.2-5.2"></path></svg>
          </button>
        </form>
        <div class="btn-group">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-circle me-2"></i>{% if user.is_authenticated %}{{ user.get_username }} {% endif %}
          </button>
          <ul class="dropdown-menu dropdown-menu-end">
            {% if user.is_authenticated %}
              <li><a href="{% url 'users-profile' %}" class="dropdown-item">Профиль {{ user.get_username }}</a></li>
              <li><a href="{% url 'add_post' %}" class="dropdown-item">Добавить объявление</a></li>
              <li><a href="{% url 'user_posts' %}" class="dropdown-item">Мои объявления</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a href="{% url 'home' %}" class="dropdown-item">Помощь</a></li>
              <li><a href="{% url 'logout' %}" class="dropdown-item">Выйти</a></li>
            {% else %}
              <a type="button" class="dropdown-item" href="{% url 'login' %}">Войти</a>
              <a type="button" class="dropdown-item" href="{% url 'users-register' %}">Регистрация</a>      
            {% endif %}
          </ul>
        </div>
      
    </header>
  </div>
  </nav>
  <!-- Navbar -->

main/templates/inc/_sidebar.html
{% load blog_tags %}
{% get_categories as categories %}
<!-- ВСЕ КАТЕГОРИИ -->

<div class="container nav-scroller  pb-3 d-lg-flex justify-content-center">
  <ul class="nav nav-pills pe-5">
    {%  for category in categories %}  
    <li class="nav-item pic">
      <a class="nav-link text-center" 
      href="{{ category.get_absolute_url }}">
        {% if category.icon %}
        <img src="{{ category.icon.url }}">
        {% endif %} 
        <p>{{ category }}</p></a>
    </li>
     <!-- {% for subcategory in category.category_set.all %}
        <li class="nav-item pic">
          <a class="nav-link" href="{{ subcategory.get_absolute_url }}">
            {% if subcategory.icon %}
            <img src="{{ subcategory.icon.url }}">
            {% endif %} 
            <p>{{ subcategory }}</p></a>
        </li>
      {% endfor %} -->
    {% endfor %}
  </ul>
  <!-- Фильтер -->
  <!-- <button type="button" class="btn btn-outline-dark" data-bs-toggle="modal" data-bs-target="#filter">
    Фильтры
  </button> -->

</div>
<!-- <div id="carouselExampleControls" class="carousel d-lg-none" data-bs-ride="carousel">
  <div class="carousel-inner">
    {%  for category in categories %}  
    <div class="carousel-item active">
      <a class="nav-link text-center" 
      href="{{ category.get_absolute_url }}">
      {% if category.icon %}
        <img src="{{ category.icon.url }}">
        {% endif %} 
        <p>{{ category }}</p>
      </a>
    </div>
    {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Предыдущий</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Следующий</span>
  </button>
</div> -->

<!-- Модальное окно -->
<div class="modal fade" id="filter" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Фильтры</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
      </div>
      <form method="GET">
        <div class="modal-body">
          {{filter.form}}
          <hr>
          <!-- <label for="formRange" class="form-label">Цена</label>
          <input type="range" class="form-range" min="0" max="100" step="1" id="formRange"
          oninput="maxPrice.value=this.value">
          Max: <input type="number" id="maxPrice" min="0" max="100"
          onkeyup="formRange.value=this.value">
          <div class="form-check mt-3">
            {% for city in view.get_city %}
            <input class="form-check-input" type="checkbox" value="{{ city }}" id="formCheckDefault">
            <label class="form-check-label" for="formCheckDefault">{{ city }}</label>
          
            {% endfor %}
          </div> -->
        
          <div class="form-check mt-3">
            {% for city in city %}
            <input class="form-check-input" type="checkbox" value="{{ city }}" id="formCheckDefault">
            <label class="form-check-label" for="formCheckDefault">{{ city }}</label>
          
            {% endfor %}
          </div>
          
          <!-- {% for city in view.get_city %}
            <span>{{ city }}</span>
          {% endfor %} -->
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Очистить все</button>
          <button type="submit" class="btn btn-dark">Найти</button>
        </div>
      </form>
    </div>
  </div>
</div>

main/templates/inc/footer.html
{% load static %}
<!--Footer-->
  <div class="container">
    <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 mt-5 border-top">
      <div class="col mb-3">
        <a href="https://repost.website" target="_blank" class=" mb-3 link-dark text-decoration-none">
          <img src="{% static 'img/r.svg' %}" alt="Производство компании Repost" class="w-25">
          <br>
        <p class="text-muted">© Продукт компании Repost<br> 2022,  Владивосток</p>
      </a>

        <p class="text-muted">Разработал Петр Осипов</p>
      </div>
  
      <div class="col mb-3">
  
      </div>
      <div class="col mb-3">
  
      </div>
     
  
      <div class="col mb-3">
        <h5>Документация</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="{% url 'confidence' %}" class="nav-link p-0 text-muted">Политика конфиденциальности</a></li>
          <li class="nav-item mb-2"><a href="{% url 'doc' %}" class="nav-link p-0 text-muted">Пользовательское соглашения</a></li>
          <li class="nav-item mb-2"><a href="{% url 'rules' %}" class="nav-link p-0 text-muted">Правила</a></li>
          <li class="nav-item mb-2"><a href="{% url 'help' %}" class="nav-link p-0 text-muted">Техподдержка</a></li>
        </ul>
      </div>
  
      <div class="col mb-3">
        <h5>Сервисы</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="https://www.moryak.site/vacancy/" class="nav-link p-0 text-muted">Вакансии</a></li>
          <li class="nav-item mb-2"><a href="https://moryak.info/" class="nav-link p-0 text-muted">Морские новости</a></li>
          <li class="nav-item mb-2"><a href="https://www.moryak.site/documents/" class="nav-link p-0 text-muted">Морские документы</a></li>
          <li class="nav-item mb-2"><a href="https://www.moryak.site/allcompany/" class="nav-link p-0 text-muted">Справочник компаний</a></li>
          <li class="nav-item mb-2"><a href="https://www.moryak.site/flot/" class="nav-link p-0 text-muted">Флот</a></li>
        </ul>
      </div>
    </footer>
  </div>
  <!--/.Footer-->

main/templates/inc/main_foto.html
<!--Section: Jumbotron-->
<section class="card wow fadeIn mb-5" style="background-image: url(static/img/t.jpg);">

  <!-- Content -->
  <div class="card-body text-white text-center py-5 px-5 my-5">

    <h1 class="mb-4">
      <strong>1й МОРСКОЙ</strong>
    </h1>
    <p>
      <strong>Маркетплейс водной техники и запчастей</strong>
    </p>
    
    <p class="mb-4">
      <strong>Более 500 000 объявлений. Покупайте и продавате судной любого размера.</strong>
    </p>
    <a target="_blank" href="{% url 'add_post' %}" class="btn btn-outline-light btn-lg">Опубликовать объявление
      <i class="fas fa-graduation-cap ml-2"></i>
    </a>

  </div>
  <!-- Content -->
</section>

main/templates/inc/user_nav.html
<div class="">
  <ul class="nav nav-pills flex-lg-column mb-auto ">
    <li class="nav-item">
      <a href="{% url 'users-profile' %}" 
        class="nav-link {% if request.resolver_match.url_name == 'users-profile' %}active{% endif %}"
        aria-current="page">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
        Профиль
      </a>
    </li>
    <li class="nav-item">
      <a href="{% url 'user_posts' %}" 
        class="nav-link {% if request.resolver_match.url_name == 'user_posts' %}active{% endif %}">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
        Мои объявления
      </a>
    </li>
    <li class="nav-item">
      <a href="{% url 'add_post' %}" 
        class="nav-link {% if request.resolver_match.url_name == 'add_post' %}active{% endif %}">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
        Добавить объявление
      </a>
    </li>
    <li class="nav-item">
      <a href="{% url 'password_change' %}" class="nav-link ">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
        Сменить пароль
      </a>
    </li>
</ul>
</div>